name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  stacked: ^3.4.4
  stacked_hooks: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Monterrat
      fonts:
        - asset: fonts/monterrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/monterrat/Montserrat-Medium.ttf
          weight: 400
        - asset: fonts/monterrat/Montserrat-Regular.ttf
          weight: 500
        - asset: fonts/monterrat/Montserrat-Bold.ttf
          weight: 600
        - asset: fonts/monterrat/Montserrat-SemiBold.ttf
          weight: 700
        - asset: fonts/monterrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/monterrat/Montserrat-Black.ttf
          weight: 900